#!/bin/sh
#SBATCH --account=epic-ps
#SBATCH --qos=batch
#SBATCH --partition=service
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=12
#SBATCH --time=120
#SBATCH --job-name="ctest_intel"
#SBATCH --exclusive

#
#source ./machines/orion_intel.env 
module use ../../modulefiles
module load build_orion_intel 
module load wflow_orion
conda activate regional_workflow

#
ctest
#ctest -VV -R test_regional_workflow
